filename: weakpoint.md
theme: clean
google-font: 
  font1: Eater
  font2:
meta:
  title: WeakPoint
  subtitle: Weak is more powerful
  author: onesuper
  email: onesuperclark@gmail.com
  organization: Central Park
slide:
  navi: true
  ribbon: true
