filename: weakpoint.md
theme: clean
googlefonts: Eater
meta:
  title: WeakPoint
  subtitle: Weak is more powerful
  author: onesuper
  email: onesuperclark@gmail.com
  organization: People Square
slide:
  navi: true
  ribbon: true
  latex: true
  mode: fade         # in { horizontal, vertical, fade }
  speed: 200