filename: weakpoint.md
theme: clean
googlefonts: Eater
meta:
  title: WeakPoint
  subtitle: Weak is more powerful
  author: onesuper
  email: onesuperclark@gmail.com
  organization: Central Park
slide:
  navi: true
  ribbon: true
