filename: weakpoint.md
theme: clean
googlefonts: Eater
google-analytics: UA-33272534-1
disqus:


meta:
  title: WeakPoint
  subtitle: Weak is more powerful
  author: onesuper
  organization: WTO
  gravatar: true
  contact:
    email: onesuperclark@gmail.com
    twitter: chengyichao
    github: onesuper
    
slide:
  navi: true
  ribbon: true
  latex: true
  